lang: en-GB # Site language
title: "Mallow" # Site name; SEO
description: "Mallow is a simple one-pager theme that puts emphesis on simplicty and speed." # Site description; SEO
author: "doamatto" # For SEO
favicon: "/assets/logo.svg" # Add a favicon.

navigation: # Control the Navigation Bar
  - title: Home
    url: /
  - title: About
    url: "#about-mallow"
  - title: Creators
    url: "#about-creators"

webSource: "https://github.com/doamatto/mallow-theme" # Contribution Link
copyrightName: [ "doamatto" ] # Text for after copyright
copyrightYear: [ "2018-2020" ] # Overwrite the updating year counter
footerLinks: # Control the Footer Links
  - title: Contact.
    url: "https://doamatto.xyz/contact"

# Don't edit below this line

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - nano.gemspec
  - .jekyll-cache

plugins:
  - jekyll
  - jekyll-sass-converter
  - jekyll-sitemap
  
sass:
  style: compressed
  sass_dir: _sass

permalink: pretty