# Read more on how to setup your instance of Mallow: https://github.com/doamatto/mallow-theme/wiki

# Configure your SEO: https://github.com/doamatto/mallow-theme/wiki/Configuring-SEO
lang: en-GB 
title: "Mallow for Jekyll"
description: "Mallow is a simple one-pager theme that puts emphesis on simplicty and speed."
author: "doamatto"
favicon: "/assets/logo.svg"
url: "https://doamatto.xyz/mallow-theme"

# Setup site verifications: https://github.com/doamatto/jekylltemplate/wiki/Site-Verifications
alexaverify: ""
bingverify: ""
dailyverify: ""
googleverify: ""
nortonverify: ""
specificverify: ""
pinverify: ""
plingverify: ""
wotverify: ""
yandexverify: ""

# Setup site analytics: https://github.com/doamatto/jekylltemplate/wiki/Analytics
simpleanalytics: false 
fathomanalytics: false
fathomsite: ""
customfathomurl: ""
matomoanalytics: false
matomositeid: ""
matomourl: ""
plausibleanalytics: false
customplausibleurl: ""

# Configure your navigation and footer links: https://github.com/doamatto/mallow-theme/wiki/Configuring-Navigation-and-Footer-Links
navigation:
  - title: Home
    url: /
  - title: Installation
    url: "https://github.com/doamatto/mallow-theme#installation"
  - title: Creators
    url: "/about-creators"
footerLinks:
  - title: Contact.
    url: "https://doamatto.xyz/contact"
webSource: "https://github.com/doamatto/mallow-theme"
copyrightName: [ "doamatto" ]
copyrightYear: [ "2018-2020" ]

# Don't edit below this line without knowing what you're doing
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache

feed:
  excerpt_only: false
  path: atom.xml

plugins:
  - jekyll
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  
sass:
  style: compressed
  sass_dir: _sass

permalink: pretty
