# Read more on how to setup your instance of Mallow: https://github.com/doamatto/mallow-theme/wiki

# Configure your SEO: https://github.com/doamatto/mallow-theme/wiki/Configuring-SEO
lang: en-GB 
title: "Mallow for Jekyll"
description: "Mallow is a simple one-pager theme that puts emphesis on simplicty and speed."
author: "doamatto"
favicon: "/assets/logo.svg"
url: "https://doamatto.xyz/mallow-theme"

# Configure your navigation and footer links: https://github.com/doamatto/mallow-theme/wiki/Configuring-Navigation-and-Footer-Links
navigation:
  - title: Home
    url: /
  - title: Installation
    url: "https://github.com/doamatto/mallow-theme#installation"
  - title: Creators
    url: "/about-creators"
footerLinks:
  - title: Contact.
    url: "https://doamatto.xyz/contact"
webSource: "https://github.com/doamatto/mallow-theme"
copyrightName: [ "doamatto" ]
copyrightYear: [ "2018-2020" ]

# Don't edit below this line
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - nano.gemspec
  - .jekyll-cache

plugins:
  - jekyll
  - jekyll-sass-converter
  - jekyll-sitemap
  
sass:
  style: compressed
  sass_dir: _sass

permalink: pretty